FROM node:16-alpine

USER node

RUN mkdir -p /home/node/app
WORKDIR /home/node/app

COPY --chown=node:node ./package.json ./
RUN npm install
# if you use docker-compose is not necesary but let it
# because one day you can decide to not use it
# or reminder for production
# or a reference for myself in the future.
COPY --chown=node:node ./ ./ 

CMD [ "npm","run","start" ]